name: domain
publish_to: none
resolution: workspace
environment:
  sdk: ^3.11.0
dependencies:
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
dev_dependencies:
  freezed: ^3.0.6
  riverpod_generator: ^2.6.5
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  lints: ^6.0.0
