name: system
publish_to: none
resolution: workspace
environment:
  sdk: ^3.11.0
dependencies:
  dio: ^5.8.0+1
  retrofit: 4.4.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
dev_dependencies:
  retrofit_generator: ^9.1.10
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  lints: ^6.0.0
